# Welcome to Jekyll!
#
#
remote_theme: mmistakes/so-simple-theme
locale: en-US
title: "Open Source Lore"
description: "Have an article you want to share? Send a pull request!"
baseurl: "" # the subpath of the site
url: "https://opensourcelore.com" # the base hostname & protocol
logo: "/assets/images/icon.svg" # path of site logo
date_format: "%B %-d, %Y"
copyright: "&copy; opensourcelore.com 2019. Made with <3; Powered by [Jekyll](https://jekyllrb.com/) & [So Simple](https://github.com/mmistakes/so-simple-theme/)"
read_time: true # reading time estimates
words_per_minute: 100 # Halved this to account for 
mathjax: false # MathJax equations
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square

